no message

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,16 +34,16 @@ jobs:
             - node_modules
           key: v1-dependencies-{{ checksum "package.json" }}
 
-      - run:
-          shell: "/bin/bash -eo pipefail"
-          name: Start docker-compose
-          command:  |
-            cd api
-            set -x
-            docker-compose build --build-arg BRANCH=${CIRCLE_BRANCH} update
-            docker-compose up -d
-            docker run --network container:api_tomcat_1 \
-              appropriate/curl -4 --retry 10 --retry-delay 20 --retry-connrefused http://localhost:8080/api/authInfo
+      # - run:
+      #     shell: "/bin/bash -eo pipefail"
+      #     name: Start docker-compose
+      #     command:  |
+      #       cd api
+      #       set -x
+      #       docker-compose build --build-arg BRANCH=${CIRCLE_BRANCH} update
+      #       docker-compose up -d
+      #       docker run --network container:api_tomcat_1 \
+      #         appropriate/curl -4 --retry 10 --retry-delay 20 --retry-connrefused http://localhost:8080/api/authInfo
 
       - run:
           shell: "/bin/bash -eo pipefail"
@@ -61,6 +61,7 @@ jobs:
           name: Run tests
           command: |
             echo ${TESTRUNID}
+            echo ${TEST}
             export NVM_DIR="/opt/circleci/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             sudo mkdir allure-results
